# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AloeStackView'
  pod 'YogaKit', :git => 'https://github.com/facebook/yoga.git', :commit => '3f7d03b4438f5b0a308e2187b7f7e3067b4f64b8'

  # Pods for Example

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
