disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - line_length
  - vertical_whitespace
  - trailing_whitespace
  - type_name

opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Grafitti
  - Metal
  - Supporting Files
included:
  - PINNA System iOS

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
