site_name: Whipcream UI
theme:
    name: material
    palette:
        primary: 'red'
        accent: 'red'
markdown_extensions:
    - admonition
    - footnotes
    - codehilite
nav:
    - 'Welcome': 'index.md'
    - 'Install':
        - 'Carthage': 'install/carthage.md'
        - 'CocoaPods': 'install/cocoapods.md'
    - 'Layout':
        - 'WhipViewStack': 'layout/WhipViewStack.md'
        - 'WhipLayoutStack': 'layout/WhipLayoutStack.md'
    